name: AI4Life_OC2_2024_26
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.3=py312haa95532_0
  - aiohttp=3.10.5=py312h827c3e9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - ansi2html=1.9.1=py312haa95532_0
  - anyio=4.6.0=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h4389bb4_5
  - arrow=1.3.0=pyhd8ed1ab_0
  - assimp=5.4.3=hf1e84b2_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.6.2=py312haa95532_0
  - blosc=1.21.6=h85f69ea_0
  - brotli=1.0.9=ha925a31_2
  - brotli-python=1.1.0=py312h275cf98_2
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2024.11.26=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h32b962e_3
  - certifi=2024.12.14=py312haa95532_0
  - cffi=1.17.1=py312h4389bb4_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=py312haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py312hd5eb7cc_2
  - cpython=3.12.6=py312hd8ed1ab_1
  - cuda-cccl_win-64=12.4.127=haa95532_2
  - cuda-cudart-dev_win-64=12.4.127=hd77b12b_0
  - cuda-cudart-static_win-64=12.4.127=hd77b12b_0
  - cuda-cudart_win-64=12.4.127=hd77b12b_0
  - cuda-nvrtc=12.4.127=hd77b12b_1
  - cuda-version=12.4=hbda6634_3
  - cupy=13.3.0=py312h584ea29_2
  - cupy-core=13.3.0=py312h2a51dd3_2
  - dash=2.14.2=py312haa95532_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.5=py312h275cf98_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.3.0=h63175ca_0
  - eigen=3.4.0=h59b6b97_0
  - embree=4.3.3=ha827246_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=he0c23c2_0
  - fastrlock=0.8.3=py312h275cf98_0
  - ffmpeg=6.1.2=gpl_h9673905_705
  - flask=3.0.3=py312haa95532_0
  - flask-compress=1.13=py312haa95532_0
  - fmt=11.0.2=h7f575de_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.12.1=hdaf720e_2
  - frozenlist=1.5.0=py312h827c3e9_0
  - gl2ps=1.4.2=had7236b_1
  - glew=2.1.0=hd77b12b_3
  - glfw=3.4=hcfcfb64_0
  - graphite2=1.3.13=h63175ca_1003
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=9.0.0=h2bedf89_1
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.4=nompi_hd5d9e70_101
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_0
  - imath=3.1.12=hbb528cf_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - imutils=0.5.4=py312h2e8e312_4
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.27.0=pyh7428d3b_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - itsdangerous=2.2.0=py312haa95532_0
  - jasper=4.2.4=hcb1a123_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsoncpp=1.9.6=hc790b64_0
  - jsonpointer=3.0.0=py312h2e8e312_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh5737063_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - khronos-opencl-icd-loader=2024.05.08=hc70643c_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240722.0=cxx17_he0c23c2_1
  - libaec=1.1.3=h63175ca_0
  - libasprintf=0.22.5=h5728263_3
  - libblas=3.9.0=25_win64_mkl
  - libboost=1.86.0=h444863b_2
  - libcblas=3.9.0=25_win64_mkl
  - libclang13=19.1.1=default_ha5278ca_0
  - libcublas=12.4.5.8=hd77b12b_1
  - libcufft=11.2.1.3=hd77b12b_1
  - libcurand=10.3.5.147=hd77b12b_1
  - libcurl=8.10.1=h1ee3ff0_0
  - libcusolver=11.6.1.9=hd77b12b_1
  - libcusparse=12.3.1.170=hd77b12b_1
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.2=h8ffe710_5
  - libgettextpo=0.22.5=h5728263_3
  - libglib=2.82.1=h7025463_1
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=25_win64_mkl
  - liblapacke=3.9.0=25_win64_mkl
  - liblzf=3.6=h2466b09_3
  - libnetcdf=4.9.2=nompi_he239ae6_115
  - libnvjitlink=12.4.127=hd77b12b_1
  - libogg=1.3.5=h2bbff1b_1
  - libopencv=4.10.0=qt6_py312hc9aa368_608
  - libopenvino=2024.4.0=hfe1841e_1
  - libopenvino-auto-batch-plugin=2024.4.0=h04f32e0_1
  - libopenvino-auto-plugin=2024.4.0=h04f32e0_1
  - libopenvino-hetero-plugin=2024.4.0=h372dad0_1
  - libopenvino-intel-cpu-plugin=2024.4.0=hfe1841e_1
  - libopenvino-intel-gpu-plugin=2024.4.0=hfe1841e_1
  - libopenvino-ir-frontend=2024.4.0=h372dad0_1
  - libopenvino-onnx-frontend=2024.4.0=h5707d70_1
  - libopenvino-paddle-frontend=2024.4.0=h5707d70_1
  - libopenvino-pytorch-frontend=2024.4.0=he0c23c2_1
  - libopenvino-tensorflow-frontend=2024.4.0=hf4e5e90_1
  - libopenvino-tensorflow-lite-frontend=2024.4.0=he0c23c2_1
  - libopus=1.3.1=h8ffe710_1
  - libpng=1.6.44=h3ca93ac_0
  - libprotobuf=5.27.5=hcaed137_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.46.1=h2466b09_0
  - libssh2=1.11.0=h7dfc565_0
  - libtheora=1.1.1=h8cc25b3_3
  - libtiff=4.7.0=hfc51747_1
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.12.7=h0f24e4e_4
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_1
  - loguru=0.7.2=py312haa95532_1
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.5=py312h4389bb4_1
  - matplotlib-base=3.9.2=py312h90004f6_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - minizip=4.0.6=hb638d1e_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2024.2.2=h66d3029_14
  - msgpack-python=1.0.3=py312h59b6b97_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.1.0=py312h827c3e9_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nlohmann_json=3.11.2=h6c2663c_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - open3d=0.18.0=py312h56a7db3_14
  - opencv=4.10.0=qt6_py312ha27ebe4_608
  - openexr=3.2.2=h9aba623_2
  - openh264=2.4.1=h63175ca_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.4.0=h2466b09_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.44=h3d7b363_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h381445a_1
  - pip=24.2=py312haa95532_0
  - pixman=0.43.4=h63175ca_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - plotly=5.24.1=py312hfc267ef_0
  - proj=9.5.0=hd9569ee_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - propcache=0.2.0=py312h827c3e9_0
  - psutil=6.0.0=py312h4389bb4_1
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=h2466b09_4
  - pugixml=1.14=h63175ca_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-opencv=4.10.0=qt6_py312h77cd176_608
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.12.6=hce54a09_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.2=pyhd8ed1ab_0
  - pywin32=306=py312h53d5487_2
  - pywinpty=2.0.13=py312h275cf98_1
  - pyyaml=6.0.2=py312h4389bb4_1
  - pyzmq=26.2.0=py312hd7027bb_2
  - qhull=2020.2=h59b6b97_2
  - qt6-main=6.7.3=hfb098fa_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - retrying=1.3.3=pyhd3eb1b0_2
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.20.0=py312h2615798_1
  - scipy=1.14.1=py312h1f4e10d_0
  - send2trash=1.8.3=pyh5737063_0
  - setuptools=74.1.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=h23299a8_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=2.2.1=he0c23c2_0
  - tbb=2021.13.0=hc790b64_0
  - tbb-devel=2021.13.0=h053bfa6_0
  - tenacity=9.0.0=py312haa95532_0
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tinyobjloader=1.0.7=h63175ca_2
  - tk=8.6.13=h5226925_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4.1=py312h4389bb4_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240906=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.1.0=py312h2bbff1b_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - utfcpp=3.2.1=haa95532_0
  - vc=14.3=h8a93ad2_21
  - vc14_runtime=14.40.33810=ha82c5b3_21
  - vs2015_runtime=14.40.33810=h3bf8584_21
  - vtk-base=9.3.1=qt_py312h72d5e3f_209
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - werkzeug=3.0.6=py312haa95532_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - win32_setctime=1.1.0=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - wslink=2.2.1=pyhd8ed1ab_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-kbproto=1.0.7=hcd874cb_1002
  - xorg-libx11=1.8.9=h0076a8d_1
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xorg-xextproto=7.3.0=hcd874cb_1003
  - xorg-xproto=7.0.31=hcd874cb_1007
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.18.0=py312h827c3e9_0
  - zeromq=4.3.5=he1f189c_5
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_1
  - zstandard=0.23.0=py312h7606c53_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - big-fish==0.6.2
      - cellpose==3.0.11
      - configargparse==1.7
      - cycler==0.12.1
      - fastremap==1.15.0
      - filelock==3.16.1
      - flow-vis==0.1
      - fonttools==4.54.0
      - fsspec==2024.9.0
      - imagecodecs==2024.9.22
      - imageio==2.36.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - mpmath==1.3.0
      - mrc==0.3.1
      - natsort==8.4.0
      - networkx==3.3
      - numba==0.60.0
      - numpy==1.26.4
      - pandas==2.2.3
      - probreg==0.3.8
      - pybind11==2.13.6
      - pyparsing==3.1.4
      - pyqt6==6.7.1
      - pyqt6-qt6==6.7.2
      - pyqt6-sip==13.8.0
      - pyqtgraph==0.13.7
      - qtpy==2.4.1
      - roifile==2024.9.15
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - superqt==0.6.7
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - torch==2.4.1
      - tqdm==4.66.5
      - transforms3d==0.4.2
      - tzdata==2024.2
prefix: C:\Users\kristinal\Anaconda3\envs\AI4Life_OC2_2024_26
